checkoutSCM:
-
    scm: import
    url: linux/config
    
multiPackage:
    kernelconfig:
        buildScript: |
            rsync -a --delete $1/mct.defconfig .
        packageScript: |
            cp -a $1/* .
